require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*

Layout/LineLength:
  IgnoredPatterns: ['^ *#']

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Style/MixinUsage:
  Exclude:
    - bin/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/*_helper.rb"
    - "spec/support/**/*.rb"
    - "config/**/*.rb"

# TODO: Enabled rule after upgrade rails to 6.1
# https://github.com/rubocop-hq/rubocop-rails/issues/110
Rails/ReversibleMigration:
  Enabled: false

# TODO: Enabled rule after upgrade rails to 6.1
# https://github.com/rubocop-hq/rubocop-rails/issues/110
Rails/BulkChangeTable:
  Enabled: false
