AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*
    - node_modules/**/*

Layout/LineLength:
  Max: 80
  IgnoredPatterns: ['^ *#']
  Exclude:
    - Schemafile

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - Schemafile

Naming/FileName:
  Exclude:
    - Schemafile

Style/MixinUsage:
  Exclude:
    - bin/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/*_helper.rb"
    - "spec/support/**/*.rb"
    - "config/**/*.rb"
