jobs:
  include:
    - stage: lint
      language: ruby
      cache: bundler
      script:
        - bundle exec rubocop
        - bundle exec brakeman
        - bundle exec slim-lint app/views
        - curl -L https://git.io/misspell | bash && git ls-files | xargs bin/misspell --error

    - stage: test
      language: minimal
      env:
        - COMPOSE_FILE=docker-compose.test.yml
      services:
        - docker
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - docker-compose run --rm sut
      after_script:
        - sudo sed -ie "s|/hackaru|$(pwd)|" coverage/.resultset.json
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: push
      language: minimal
      if: tag =~ ^v
      services:
        - docker
      script:
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        - |
          TAGS=(
            "latest" \
            "$(echo "$TRAVIS_TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1/')" \
            "$(echo "$TRAVIS_TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1.\2/')" \
            "$(echo "$TRAVIS_TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1.\2.\3/')" \
          )
          for TAG in ${TAGS[@]}; do
            docker build . -t "$DOCKER_REPO_NAME:$TAG"
            docker push "$DOCKER_REPO_NAME:$TAG"
          done
