jobs:
  include:
    - stage: lint
      language: ruby
      cache: bundler
      script:
        - bundle exec rubocop
        - bundle exec brakeman
        - bundle exec slim-lint app/views

    - stage: test
      language: minimal
      env:
        - COMPOSE_FILE=docker-compose.test.yml
      services:
        - docker
      script:
        - docker-compose run --rm sut
      after_success:
        - sudo sed -ie "s|/hackaru|$(pwd)|" coverage/.resultset.json
        - bash <(curl -s https://codecov.io/bash) -f coverage/.resultset.json -Z

    - stage: push
      language: minimal
      if: tag =~ ^v
      services:
        - docker
      script:
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        - |
          TAGS=(
            "latest" \
            "$(echo "$TRAVIS_TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1/')" \
            "$(echo "$TRAVIS_TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1.\2/')" \
            "$(echo "$TRAVIS_TAG" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1.\2.\3/')" \
          )
          for TAG in ${TAGS[@]}; do
            docker build . -t "$DOCKER_REPO_NAME:$TAG"
            docker push "$DOCKER_REPO_NAME:$TAG"
          done
