version: '3'
services:
  api:
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    env_file: .env.development
    stdin_open: true
    tty: true
    volumes:
      - .:/hackaru:cached
      - ./tmp/app:/hackaru/tmp:cached
      - /hackaru/node_modules

  webpack:
    build: .
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    env_file: .env.development
    command: bin/webpack-dev-server
    volumes:
      - ./app/javascript:/hackaru/app/javascript
      - ./public/:/hackaru/public
    ports:
      - 3035:3035

  sidekiq:
    env_file: .env.development
    command: bundle exec sidekiq
      -c 3
      -q hackaru-api_development_default
      -q hackaru-api_development_mailers
    volumes:
      - .:/hackaru
      - ./tmp/sidekiq:/hackaru/tmp
      - /hackaru/node_modules

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
