version: '3'
services:
  api:
    env_file: .env.development
    stdin_open: true
    tty: true
    user: root
    volumes:
      - .:/hackaru:delegated
      - /hackaru/tmp
      - /hackaru/node_modules

  webpack:
    build: .
    env_file: .env.development
    command: yarn dev
    volumes:
      - ./app/assets:/hackaru/app/assets:delegated
      - ./public/packs:/hackaru/public/packs:delegated
      - ./webpack.common.js:/hackaru/webpack.common.js:delegated
      - ./webpack.dev.js:/hackaru/webpack.dev.js:delegated
      - ./package.json:/hackaru/package.json:delegated

  sidekiq:
    env_file: .env.development
    user: root
    command: bundle exec sidekiq
      -c 1
      -q hackaru-api_development_default
      -q hackaru-api_development_mailers
    volumes:
      - .:/hackaru:delegated
      - /hackaru/tmp
      - /hackaru/node_modules

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
