default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER', 'postgresql') %>
  encoding: <%= ENV.fetch('DB_ENCODING', 'unicode') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASS', '') %>

development:
  <<: *default
  database: hackaru-api_development

test:
  <<: *default
  database: hackaru-api_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE', 'hackaru-api_production') %>
