default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER', 'postgresql') %>
  encoding: <%= ENV.fetch('DB_ENCODING', 'unicode') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST', '172.25.192.1') %>
  port: <%= ENV.fetch('DB_PORT', '3306') %>
  username: <%= ENV.fetch('DB_USER', 'root') %>
  password: <%= ENV.fetch('DB_PASS', '123123') %>

development:
  <<: *default
  database: hackaru-api_development

test:
  <<: *default
  database: hackaru-api_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE', 'hackaru-api_production') %>
