weekly_report_mailer_job:
  cron: '0 12 * * 0'
  class: 'ReportMailerJob'
  args:
    period: 'week'

monthly_report_mailer_job:
  cron: '0 12 1 * *'
  class: 'ReportMailerJob'
  args:
    period: 'month'
