name: slim-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-slim-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up Ruby version
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run slim-lint
        run: bundle exec slim-lint app/views
